language: android

jdk:
  - openjdk8

android:
  components:
    - tools
    - platform-tools
    - android-29
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  - ./ci-build.sh

notifications:
  email: false

branches:
  except:
    - gh-pages

sudo: false

