[versions]
kotlin_lang = "1.7.20"
kotlinx_coroutines = "1.6.4"
kotlinx_datetime = "0.4.0"
kotlinx_serialization = "1.4.1"
androidx_core = "1.7.0"
androidx_compose_bom = "2022.10.00"
androidx_compose_compiler = "1.3.2"
androidx_lifecycle = "2.4.1"
androidx_savedstate = "1.1.0"
firebase = "20.3.1"
gitlive_firebase = "1.6.2"

[libraries]
android-gradle-plugin = "com.android.tools.build:gradle:7.4.2"
vespene = "net.mbonnin.vespene:vespene-lib:0.5"

kotlin_gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_lang" }
kotlin_serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin_lang" }
kotlinx_serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx_serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx_coroutines" }
kotlinx_datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx_datetime" }

androidx_core = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
androidx_savedstate = { module = "androidx.savedstate:savedstate-ktx", version.ref = "androidx_savedstate" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx_compose_bom" }
androidx_compose_material = { module = "androidx.compose.material:material" }
androidx_compose_material3 = { module = "androidx.compose.material3:material3" }
androidx_compose_ui = { module = "androidx.compose.ui:ui" }
androidx_compose_runtime = { module = "androidx.compose.runtime:runtime" }
androidx_compose_foundation = { module = "androidx.compose.foundation:foundation" }
androidx_compose_uitooling = { module = "androidx.compose.ui:ui-tooling" }
androidx_lifecycle_viewmodel_compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx_lifecycle" }
androidx_lifecycle_runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx_lifecycle" }
androidx_lifecycle_viewmodel_ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx_lifecycle" }

firebase_common = { module = "com.google.firebase:firebase-common", version.ref = "firebase" }

gitlive_firebase_app = { module = "dev.gitlive:firebase-app", version.ref = "gitlive_firebase" }
gitlive_firebase_auth = { module = "dev.gitlive:firebase-auth", version.ref = "gitlive_firebase" }
gitlive_firebase_firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "gitlive_firebase" }
gitlive_firebase_common = { module = "dev.gitlive:firebase-common", version.ref = "gitlive_firebase" }
